"""Riven API Server - HTTP API for core management and messaging."""

import json
from typing import Optional
from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from shard_manager import get_manager, ShardManager
from shard import get_shard


# ============== MODELS ==============

class SessionCreate(BaseModel):
    session_id: str  # Client must provide this
    shard_name: Optional[str] = None


class MessageSend(BaseModel):
    message: str
    stream: bool = False
    shard_name: str = "code_hammer"


# ============== API ==============

app = FastAPI(title="Riven API", version="1.0.0")
manager: ShardManager = get_manager()


@app.get("/")
def root():
    """Health check."""
    return {"status": "ok", "riven": "codehammer"}


@app.get("/api/v1/shards")
def list_shards():
    """List available shards."""
    return {"shards": manager.list()}


@app.post("/api/v1/sessions")
def create_session(req: SessionCreate):
    """Create a session with client-provided session_id.
    
    The session_id is generated by the client and passed in.
    """
    result = manager.start(session_id=req.session_id, shard_name=req.shard_name)
    if not result.get("ok"):
        raise HTTPException(400, result.get("message"))
    return {
        "session_id": req.session_id,
        "shard_name": result.get("shard_name"),
        "ok": True
    }


@app.get("/api/v1/sessions")
def list_sessions():
    """List running sessions."""
    return {"sessions": manager.list_sessions()}


@app.get("/api/v1/sessions/{session_id}")
def get_session(session_id: str):
    """Get session info."""
    if not manager.session_exists(session_id):
        raise HTTPException(404, "Session not found")
    return {
        "session_id": session_id,
        "shard_name": manager.get_current(),
    }


@app.delete("/api/v1/sessions/{session_id}")
def delete_session(session_id: str):
    """Stop a session."""
    result = manager.stop(session_id)
    return result


@app.post("/api/v1/sessions/{session_id}/messages")
async def send_message(session_id: str, req: MessageSend):
    """Send a message. Stream or get result.
    
    - stream=true: SSE with tokens as they arrive
    - stream=false: JSON with full output when done
    
    Session ID is used for memory persistence (not stored in manager).
    """
    # Get shard_name from request or default
    shard_name = req.shard_name or "code_hammer"
    
    if req.stream:
        # Streaming mode - yield tokens via SSE
        async def generate():
            try:
                shard = get_shard(shard_name, session_id)
                async for event in shard.run_stream(req.message):
                    if "error" in event:
                        yield f"data: {json.dumps({'error': event['error']})}\n\n"
                        break
                    if "token" in event:
                        yield f"data: {json.dumps({'token': event['token']})}\n\n"
                    if "tool" in event:
                        yield f"data: {json.dumps(event)}\n\n"
                    if event.get("done"):
                        yield f"data: {json.dumps({'done': True})}\n\n"
            except Exception as e:
                yield f"data: {json.dumps({'error': str(e)})}\n\n"
        
        return StreamingResponse(generate(), media_type="text/event-stream")
    
    # Non-streaming - use session's shard (persists memory)
    try:
        shard = get_shard(shard_name, session_id)
        result = await shard.run(req.message)
        output = str(result.output) if result else ""
    except Exception as e:
        raise HTTPException(500, str(e))
    
    # Session persists - client can send more messages
    return {"output": output}


@app.get("/api/v1/sessions/{session_id}/messages")
def poll_messages(session_id: str):
    """Poll for messages from a session."""
    messages = manager.receive(session_id)
    return {"messages": messages}


# ============== RUN ==============

def run(host: str = "0.0.0.0", port: int = 8080):
    """Run the API server."""
    import uvicorn
    uvicorn.run(app, host=host, port=port)


if __name__ == "__main__":
    run(host="0.0.0.0", port=8080)