"""Shard Manager - supports both simple (per-message) and threaded (persistent) modes."""

import os
import glob
import sys
import yaml
import asyncio
import threading
import queue
from typing import Optional, List, Dict
from shard import get_shard


# ============== SHARD INSTANCE (threaded mode) ==============

class ShardInstance:
    """A running shard instance with I/O queues."""
    
    def __init__(self, session_id: str, shard_name: str):
        self.session_id = session_id
        self.shard_name = shard_name
        self.input_queue: queue.Queue = queue.Queue()
        self.output_queue: queue.Queue = queue.Queue()
        self.status = "starting"
        self.thread: Optional[threading.Thread] = None


# ============== SHARD MANAGER ==============

class ShardManager:
    """Manages shards - supports simple and threaded modes."""
    
    def __init__(self):
        self._shards: Dict[str, Dict] = {}  # name -> config
        self._current_session: Optional[str] = None
        self._instances: Dict[str, ShardInstance] = {}  # session_id -> instance
        self._active_sessions: set = set()  # Track active session IDs
        self._lock = threading.Lock()
        self._mode: str = "threaded"  # "threaded" or "simple"
        self._load_shards()
    
    def _load_shards(self) -> None:
        """Load available shards from the shards/ folder."""
        shards_dir = os.path.join(
            os.path.dirname(os.path.abspath(__file__)), 
            "shards"
        )
        
        if not os.path.exists(shards_dir):
            return
        
        for filepath in glob.glob(os.path.join(shards_dir, "*.yaml")):
            with open(filepath) as f:
                config = yaml.safe_load(f)
                if config and 'name' in config:
                    name = config.pop('name')
                    self._shards[name] = config
    
    def set_mode(self, mode: str) -> None:
        """Set mode: 'threaded' for persistent shards, 'simple' for create-per-message."""
        self._mode = mode
    
    def list(self) -> List[Dict]:
        """List available shards."""
        return [
            {
                'name': name,
                'display_name': config.get('display_name', name),
                'description': config.get('description', ''),
            }
            for name, config in self._shards.items()
        ]
    
    def get(self, name: str) -> Optional[Dict]:
        """Get shard config by name."""
        return self._shards.get(name)
    
    def exists(self, name: str) -> bool:
        """Check if a shard exists."""
        return name in self._shards
    
    def session_exists(self, session_id: str) -> bool:
        """Check if a session is active."""
        with self._lock:
            return session_id in self._instances
    
    def get_current(self) -> Optional[str]:
        """Get the current session ID."""
        return self._current_session
    
    def set_current(self, session_id: str) -> str:
        """Set the current session."""
        self._current_session = session_id
        return f"Switched to session {session_id}"
    
    def start(self, session_id: str, shard_name: str = None) -> Dict:
        """Start a session. Session ID must be provided by caller."""
        # Require session_id - no generation
        if not session_id:
            return {
                "session_id": None,
                "message": "session_id is required (generated by client)",
                "ok": False
            }
        
        # Load default shard from config if not provided
        if shard_name is None:
            shard_name = self._get_default_shard()
        
        # Validate shard exists
        if shard_name not in self._shards:
            available = ", ".join(self._shards.keys())
            return {
                "session_id": None,
                "message": f"Shard '{shard_name}' not found. Available: {available}",
                "ok": False
            }
        
        self._current_session = session_id
        
        # Track this session as active
        with self._lock:
            self._active_sessions.add(session_id)
        
        if self._mode == "threaded":
            # Threaded mode: spawn background thread
            with self._lock:
                if session_id in self._instances:
                    return {
                        "session_id": session_id,
                        "message": f"Session {session_id} already running",
                        "ok": True
                    }
                
                instance = ShardInstance(session_id, shard_name)
                self._instances[session_id] = instance
                
                # Start background thread
                instance.thread = threading.Thread(
                    target=self._run_shard_thread,
                    args=(instance,),
                    daemon=True
                )
                instance.thread.start()
                
                # Wait for thread to be ready
                import time
                for _ in range(20):
                    if instance.status == "running":
                        break
                    time.sleep(0.1)
        else:
            # Simple mode: just record session
            pass
        
        display = self._shards[shard_name].get('display_name', shard_name)
        return {
            "session_id": session_id,
            "message": f"Session {session_id} ready with {display}",
            "ok": True
        }
    
    def _run_shard_thread(self, instance: ShardInstance) -> None:
        """Run shard in background thread (threaded mode)."""
        try:
            shard = get_shard(instance.shard_name, session_id=instance.session_id)
            instance.status = "running"

            while instance.status == "running":
                try:
                    msg = instance.input_queue.get(timeout=1)
                except queue.Empty:
                    continue

                if msg is None:  # Stop signal
                    break

                try:
                    result = asyncio.run(shard.run(msg))
                    output = str(result.output) if result and hasattr(result, 'output') else str(result)
                    instance.output_queue.put(output)
                except Exception as e:
                    instance.output_queue.put(f"Error: {e}")

        except Exception as e:
            import traceback
            traceback.print_exc(file=sys.stderr)
            instance.output_queue.put(f"Shard error: {e}")
        finally:
            instance.status = "stopped"
    
    def send(self, session_id: str, message: str, shard_name: str = None) -> Dict:
        """Send a message to a session."""
        if shard_name is None:
            shard_name = self._get_default_shard()
        
        if shard_name not in self._shards:
            return {"ok": False, "error": f"Shard '{shard_name}' not found"}
        
        self._current_session = session_id
        
        if self._mode == "threaded":
            # Threaded: put message in queue
            with self._lock:
                instance = self._instances.get(session_id)
                if not instance:
                    return {"ok": False, "error": f"Session '{session_id}' not found"}
                if instance.status != "running":
                    return {"ok": False, "error": f"Session not running"}
            
            instance.input_queue.put(message)
            return {"ok": True, "queued": True}
        else:
            # Simple: create shard, run, return
            try:
                shard = get_shard(shard_name, session_id=session_id)
                result = asyncio.run(shard.run(message))
                output = str(result.output) if result and hasattr(result, 'output') else str(result)
                return {"ok": True, "output": output}
            except Exception as e:
                return {"ok": False, "error": str(e)}
    

    
    def receive(self, session_id: str, timeout: float = 0.1) -> List[str]:
        """Receive messages from a session (threaded mode)."""
        messages = []
        
        with self._lock:
            instance = self._instances.get(session_id)
            if not instance:
                return []
        
        while True:
            try:
                msg = instance.output_queue.get(timeout=0.01)
                messages.append(msg)
            except queue.Empty:
                break
        
        return messages
    
    def _get_default_shard(self) -> str:
        """Get default shard name from config."""
        config_path = os.path.join(
            os.path.dirname(os.path.abspath(__file__)), 
            "config.yaml"
        )
        if os.path.exists(config_path):
            with open(config_path) as f:
                cfg = yaml.safe_load(f)
                return cfg.get('default_core', 'code_hammer')
        return 'code_hammer'
    
    def stop(self, session_id: str) -> Dict:
        """Stop a session."""
        with self._lock:
            instance = self._instances.get(session_id)
            if not instance:
                return {"message": f"Session {session_id} not found", "ok": False}
            
            instance.status = "stopping"
            instance.input_queue.put(None)  # Signal thread to stop
            
            if instance.thread and instance.thread.is_alive():
                instance.thread.join(timeout=5)
            
            del self._instances[session_id]
            
            if self._current_session == session_id:
                self._current_session = None
            
            # Remove from active sessions
            self._active_sessions.discard(session_id)
        
        return {"message": f"Session {session_id} stopped", "ok": True}
    
    def get_session(self, session_id: str) -> Optional[Dict]:
        """Get session info by ID."""
        with self._lock:
            inst = self._instances.get(session_id)
            if inst:
                return {
                    "session_id": inst.session_id,
                    "shard_name": inst.shard_name,
                    "status": inst.status,
                }
        return None
    
    def list_sessions(self) -> List[Dict]:
        """List running sessions."""
        with self._lock:
            return [
                {
                    "session_id": inst.session_id,
                    "shard_name": inst.shard_name,
                    "status": inst.status,
                }
                for inst in self._instances.values()
            ]


# ============== GLOBAL INSTANCE ==============

_manager: Optional[ShardManager] = None


def get_manager() -> ShardManager:
    """Get the global ShardManager instance."""
    global _manager
    if _manager is None:
        _manager = ShardManager()
    return _manager


# ============== CONVENIENCE FUNCTIONS ==============

def list_shards() -> List[Dict]:
    """List available shards."""
    return get_manager().list()


def start(session_id: str = None, shard_name: str = None) -> Dict:
    """Start a new session."""
    return get_manager().start(session_id, shard_name)


def stop(session_id: str) -> Dict:
    """Stop a session."""
    return get_manager().stop(session_id)


def send(session_id: str, message: str, shard_name: str = None) -> Dict:
    """Send a message to a session."""
    return get_manager().send(session_id, message, shard_name)


def receive(session_id: str, timeout: float = 0.1) -> List[str]:
    """Receive messages from a session."""
    return get_manager().receive(session_id, timeout)


def list_sessions() -> List[Dict]:
    """List running sessions."""
    return get_manager().list_sessions()


def get_session(session_id: str) -> Optional[Dict]:
    """Get session info by ID."""
    return get_manager().get_session(session_id)


def get_current_session() -> Optional[str]:
    """Get current session ID."""
    return get_manager().get_current()


def switch_session(session_id: str) -> str:
    """Switch to a different session."""
    return get_manager().set_current(session_id)


def shard_exists(name: str) -> bool:
    """Check if a shard exists."""
    return get_manager().exists(name)
